[tool.poetry]
name = "akiradb"
version = "0.0.1"
description = "A framework for Cypher instructions over PostGres Wire protocol. Supports ArcadeDB."
authors = ["Pierre Jeanjean <rhiobet@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
psycopg = "^3.0.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
